### ISSUE TITLE
API usage over Groovy scripts

### ISSUE THREAD

**Issue by brianveltman** [CloudKrafter/nexus-ansible-collection#16]
### Context
The `nexus_oss` role has reached a point where its maintainability is becoming challenging. This is primarily due to Sonatype's push towards using the API instead of Groovy scripts for configuring and managing the Nexus Repository Manager.

If you use the `config_api` role only, this topic is not an issue.

Users who are running their Nexus instances based on the `nexus_oss` role will be impacted sooner or later.

Over the last few releases we have noticed that the Groovy scripts will break frequently. Although using Groovy scripts will result in faster run times for the role. It also introduces security issues, and in some cases it can break your Nexus instance due to the lack of input/type validations.

### Proposed Change
We are considering to include/re-use the API tasks from the `config_api` role as a replacement for the Groovy scripts in the `nexus_oss` role to facilitate a solution for the Groovy changes while facilitating a migration process.

#### Example for Privileges

```yaml
    # Current task to create privileges
    - name: Create/check privileges
      ansible.builtin.include_tasks: call_script.yml
      vars:
        script_name: setup_privileges_from_list
        call_args: "{{ nexus_privileges }}"
      when: nexus_privileges | length > 0 and not nexus_use_api_for_provisioning | default(false) | bool
      tags: privileges

    # Will become this
    - name: Import Privileges task from config_api
      ansible.builtin.include_role:
        name: cloudkrafter.nexus.config_api
        tasks_from: privileges-tasks.yml
      tags: privileges
      when: nexus_privileges | length > 0

```

### Impact
The `nexus_oss` role does not enforce a **desired-state** for your nexus configuration. Where the `config_api` role will enforce a **desired-state**. Re-using the `config_api` tasks within the `nexus_oss` role will result in the deletion of repositories, routing-rules, privileges, roles, etc.. that are not defined in your Ansible variables.

This impact could be prevented by introducing another variable such as `nexus_enforce_desired_state: false` that will skip the delete tasks in the `config_api` role.

Although these changes would be substantial and would disrupt existing workflows. Moving to API usage is expected to align us better with the vendor's recommendations and might offer better long-term maintainability and support.

### Call to Action
We would like to open this topic for discussion with the users. Your feedback is crucial in making an informed decision. Please share your thoughts, concerns, and suggestions on this proposed change.

Thank you for your contribution and support!
