### ISSUE TITLE
nexus_oss failing to delete default blobstore

### ISSUE THREAD

**Issue by bgp-sz** [CloudKrafter/nexus-ansible-collection#22]
It fails for me:

    googlecompute.nexus: TASK [cloudkrafter.nexus.nexus_oss : Deleting default blobstore] ***************
    googlecompute.nexus: included: /home/sec/.ansible/collections/ansible_collections/cloudkrafter/nexus/roles/nexus_oss/tasks/delete_blobstore_each.yml for default => (item={'name': 'default'})
    googlecompute.nexus:
    googlecompute.nexus: TASK [cloudkrafter.nexus.nexus_oss : Delete blobstores using API] **************
    googlecompute.nexus: fatal: [default]: FAILED! => {"msg": "The conditional check '__nexus_existing_blobstores__ and blobstore.name in __nexus_existing_blobstores__.json | map(attribute='name') | list' failed. The error was: error while evaluating conditional (__nexus_existing_blobstores__ and blobstore.name in __nexus_existing_blobstores__.json | map(attribute='name') | list): '__nexus_existing_blobstores__' is undefined. '__nexus_existing_blobstores__' is undefined\n\nThe error appears to be in '/home/sec/.ansible/collections/ansible_collections/cloudkrafter/nexus/roles/nexus_oss/tasks/delete_blobstore_each.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Delete blobstores using API\n  ^ here\n"}

**Comment by brianveltman** [comment]
What is the full ansible command you're executing?

**Comment by fenpaws** [comment]
I also just encounterd that issue, its a fresh install as well. Here is my playbook that i run, i didnt do anything special with the command. Just a plain ansible-playbook

```yml
---
- name: Nexus
  hosts: nexus
  become: true
  collections:
  - cloudkrafter.nexus

  vars:
    nginx_enable: true
    nginx_type: "opensource"

    java_package: openjdk
    java_version: "8"

    nexus_timezone: 'UTC+1'
    nexus_application_host: '127.0.0.1'
    nexus_public_hostname: "{{ nginx_fqdn }}"
    
    nexus_privileges:
      - name: all-repos-read
        description: 'Read & Browse access to all repos'
        repository: '*'
        actions:
          - read
          - browse

  roles:
    - role: basic-settings
    - role: users
    - role: ansible-role-nginx
    - role: geerlingguy.java
    - role: cloudkrafter.nexus.nexus_oss
    - role: cloudkrafter.nexus.config_api
    - role: ansible-role-nginx-config
      vars:
        nginx_config_debug_output: true
        nginx_config_http_template_enable: true
        nginx_config_http_template:
        - template_file: http/default.conf.j2
          deployment_location: /etc/nginx/conf.d/nexus.uti.local.conf
          config:
            upstreams:
            - name: nexus
              servers:
              - address: localhost:8081
            servers:
            - core:
                server_name: "{{ nginx_fqdn }}"
                listen:
                - default_server: true
                  port: 80
                  address: 0.0.0.0
              locations:
              - location: /
                rewrite:
                  return:
                    code: 301
                    text: "https://$host$request_uri"
            - core:
                server_name: "{{ nginx_fqdn }}"
                listen:
                - default_server: true
                  port: 443
                  ssl: true
              ssl:
                certificate: "/etc/ssl/nginx/nexus.pem"
                certificate_key: "/etc/ssl/nginx/nexus.key"
              locations:
              - location: /
                proxy:
                  pass: http://nexus
                  set_header:
                  - field: Host
                    value: $host
                  - field: Connection
                    value: $http_connection
                  - field: Upgrade
                    value: $http_upgrade
                  - field: X-Real-IP
                    value: $remote_addr
                  - field: X-Forwarded-For
                    value: $proxy_add_x_forwarded_for
                  - field: X-Forwarded-Proto
                    value: $scheme
```
