### ISSUE TITLE
Nexus Download URLs changed

### ISSUE THREAD

**Issue by jzielke84** [CloudKrafter/nexus-ansible-collection#28]
The URLs have changed (again...): https://help.sonatype.com/en/download.html

Fix would be:

```yaml
- name: Register nexus package name
  ansible.builtin.set_fact:
    nexus_package: >-
      {{
        'nexus-' + nexus_version
        + '-java' + nexus_java_version | string
        + '-unix.tar.gz'
        if nexus_version is version_compare('3.67.1-01', '>=') and nexus_version is version_compare('3.70.1-02', '<=')
        else 'nexus-unix-x86-64-' + nexus_version + '.tar.gz'
      }}
```

**Comment by brianveltman** [comment]
Yes I noticed it as well last night..
Thanks for your proposed fix. I might add this as a temporarily fix/workaround. But i'm getting a bit annoyed by these url changes, so I'm thinking of creating a python module within this collection that automatically identifies the url based on a given version number.

It's probably gonna be something like this:
```yaml
- name: Download given Nexus version
  cloudkrafter.nexus.download:
    state: latest # 'latest' to download the latest version, 'present' combined with a given version.
    version: 3.78.0-1 # only works when state is present.
    dest: /path/to/download/dir
```

This is in line with the refactoring goals im currently working on.
